name: psyplot_conda
channels:
    - chilipp
    - conda-forge
dependencies:
    # psyplot
    - matplotlib
    - xarray
    - docrep
    - funcargparse
    - numpy
    # psy-simple
    - seaborn
    # psy-maps
    - cartopy
    # psy-reg
    - scipy
    - statsmodels
    # psyplot-gui
    - qtconsole
    - pyqt
    - sphinx
    - fasteners
    - sphinx
    - sphinx_rtd_theme
    # miscellaneous
    - python
    - dask
    - netcdf4
    - bottleneck
